name: 'Update Terraform Cloud Variable'
description: 'Invoke Terraform API to update Terraform variable value'
inputs:
  workSpaceName:
    description: 'Terraform workspace name'
    required: true
  organizationName:
    description: 'Terraform organization Name'
    required: true
  terraformToken:
    description: 'Terraform Token'
    required: true
  terraformHost:
    description: 'Terraform Host Name'
    required: true
  variableName:
    description: 'The variable key / name as shown in Terraform Cloud'
    required: true
  variableHCL:
    description: 'Specify true or false if variable should be in HCL format'
    required: false
  variableValue:
    description: 'The variable value to be replaced in Terraform Cloud'
    required: true
outputs:
  variableId:
    description: 'The Updated Variable ID'
runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'
